accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.SignUp.as_view(), name='signup'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

django_todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('accounts/',include('accounts.urls'))
]

todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('view/<int:pk>/', views.ViewDetail.as_view(), name='view'),
    path('create/', views.CreateTask.as_view(), name='create')

]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    CHOICES = (
        (1, 'Done'),
        (2, 'Doing'),
        (3, 'Undone'),
    )
    title = models.CharField(max_length=20)
    description = models.TextField()
    condition = models.SmallIntegerField(choices=CHOICES, default=3)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

User = get_user_model()

class SignUpForm(forms.ModelForm):
    confirm_password = forms.CharField(required=True)

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        rpassword = self.cleaned_data.get('confirm_password')
        if password != rpassword:
            raise ValidationError('Error in confirm your password')
        return rpassword

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

    class Meta:
        model = User
        fields = ('username','password')

todo/forms.py
from django import forms
from .models import Todo


class CreateNewTask(forms.ModelForm):

    def save(self, user, commit=True):
        task = super().save(commit=False)
        task.user = user
        task.save()
        return task

    class Meta:
        model = Todo
        exclude = ('user',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignUpForm


class Login(auth_views.LoginView):
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')
        return super().dispatch(request, *args, **kwargs)


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'sign_up.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        return render(self.request, 'sign_up.html', context={'success': True, 'form': self.form_class()})


class Logout(auth_views.LogoutView):
    next_page = reverse_lazy('login')

todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, UpdateView, DetailView, CreateView
from .forms import CreateNewTask
from .models import Todo


class Index(LoginRequiredMixin, ListView):
    paginate_by = 10
    page_kwarg = 'pg'
    template_name = 'todo.html'
    context_object_name = 'todo_list'

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)


class Edit(LoginRequiredMixin, UpdateView):
    template_name = 'edit.html'
    fields = ('title', 'description', 'condition')

    def get_object(self, queryset=None):
        res = get_object_or_404(Todo, pk=self.kwargs['pk'])
        if res.user != self.request.user:
            raise Http404
        return res

    def get_success_url(self):
        return reverse('view', kwargs={'pk': self.object.pk})


class ViewDetail(LoginRequiredMixin, DetailView):
    template_name = 'view.html'

    def get_object(self, queryset=None):
        res = get_object_or_404(Todo, pk=self.kwargs['pk'], user=self.request.user)
        if res.user != self.request.user:
            raise Http404
        return res


class CreateTask(LoginRequiredMixin, CreateView):
    form_class = CreateNewTask
    template_name = 'create.html'

    def form_valid(self, form):
        self.object = form.save(self.request.user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('view', kwargs={'pk': self.object.pk})

templates/create.html
{% extends 'edit.html' %}
{% block title %}create{% endblock %}

templates/edit.html
{% extends 'todo.html' %}
{% load widget_tweaks %}
{% block title %}Edit{% endblock %}
{% block body %}
    <form method="post" class="container">{% csrf_token %}
        <div class="mb-3">
            <label class="form-label fs-4">{{ form.title.label }}</label>
            {% render_field form.title class="form-control fs-5" %}
        </div>
        {% if form.title.errors %}
            <div class="alert alert-warning">
                {{ form.title.errors }}
            </div>
        {% endif %}
        <div class="mb-3">
            <label class="form-label fs-4">{{ form.description.label }}</label>
            {% render_field form.description class="form-control fs-5" %}
        </div>
        {% if form.description.errors %}
            <div class="alert alert-warning">
                {{ form.description.errors }}
            </div>
        {% endif %}
        <div class="mb-3">
            <label class="form-label fs-4">{{ form.condition.label }}</label>
            {% render_field form.condition class="form-select" %}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

templates/login.html
{% extends 'todo.html' %}
{% load widget_tweaks %}
{% block title %}login{% endblock %}
{% block body %}
    <form method="post" class="container" style="max-width: 40rem;margin: 2rem auto;">{% csrf_token %}
        <div class="mb-3 input-group input-group-lg" style="padding:10px 10px 0 0;">
            <span class="input-group-text">username</span>
            {% render_field form.username class="form-control fs-6" %}
        </div>
        {% if form.username.errors %}
            <div class="alert alert-warning">
                {{ form.username.errors }}
            </div>
        {% endif %}
        <div class="mb-3 input-group input-group-lg" style="padding: 10px 10px 0 0;">
            <span class="input-group-text">password</span>
            {% render_field form.password class="form-control fs-6" placholder="password" %}
        </div>
        {% if form.password.errors %}
            <div class="alert alert-warning">
                {{ form.password.errors }}
            </div>
        {% endif %}
        {% if form.password.errors %}
            <div class="alert alert-warning">
                {{ form.password.errors }}
            </div>
        {% elif form.errors %}
            <div class="alert alert-warning">
                {% for error in form.errors.values %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        <button type="submit" class="btn btn-lg btn-primary" style="margin: 0 auto">Login</button>
    </form>
{% endblock %}

templates/sign_up.html
{% extends 'todo.html' %}
{% load widget_tweaks %}
{% block title %}SignUp{% endblock %}
{% block body %}
    <form method="post" class="container" style="max-width: 40rem;">{% csrf_token %}
        <div class="mb-3">
            <label class="form-label fs-4">{{ form.username.label }}</label>
            {% render_field form.username class="form-control fs-5" %}
        </div>
        {% if form.username.errors %}
            <div class="alert alert-warning">
                {{ form.username.errors }}
            </div>
        {% endif %}
        <div class="mb-3">
            <label class="form-label fs-4">{{ form.password.label }}</label>
            {% render_field form.password type="password" class="form-control fs-5" %}
        </div>
        {% if form.password.errors %}
            <div class="alert alert-warning">
                {{ form.password.errors }}
            </div>
        {% endif %}
        <div class="mb-3">
            <label class="form-label fs-4">{{ form.confirm_password.label }}</label>
            {% render_field form.confirm_password type="password" class="form-control fs-5" %}
        </div>
        {% if success %}
            <div class="alert alert-success">
                success
            </div>
        {% endif %}
        <button class="btn btn-dark" type="submit">SignUp</button>
    </form>
{% endblock %}

templates/todo.html
{% load static %}
{% load paginator_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <title>{% block title %}Todo{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <h3><span class="navbar-brand badge bg-secondary">TO-DO</span></h3>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Tasks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'create' %}">Add Task</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                <div class="d-flex">
                    <a class="btn btn-success" href="{% url 'logout' %}">Logout</a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>
{% block body %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Condition</th>
            <th scope="col">Change condition</th>
        </tr>
        </thead>
        <tbody>
        {% for object in todo_list %}
            <tr>
                <td>{{ object.title }}</td>
                <td>{{ object.description|slice:":10" }}...</td>
                <td><span class="badge bg-primary">{{ object.get_condition_display }}</span></td>
                <td>
                    <a class="btn btn-sm btn-outline-primary" href="{% url 'edit' object.pk %}">Edit</a>
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'view' object.pk %}">View</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <br/>
        <nav class="d-md-flex justify-content-md-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'index' %}?pg={{ page_obj.previous_page_number }}"
                           aria-label="Previous">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" aria-label="Previous">&laquo;</a>
                    </li>
                {% endif %}
                {% get_proper_elided_page_range paginator page_obj.number as page_range %}
                {% for page_num in page_range %}
                    {% if page_obj.number == page_num %}
                        <li class="page-item active"><a class="page-link"
                                                        href="{% url 'index' %}?pg={{ page_num }}">{{ page_num }}</a>
                        </li>
                    {% elif page_num == paginator.ELLIPSIS %}
                        <li class="page-item"><span class="page-link">{{ paginator.ELLIPSIS }}</span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link"
                                                 href="{% url 'index' %}?pg={{ page_num }}">{{ page_num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'index' %}?pg={{ page_obj.next_page_number }}"
                           aria-label="Previous">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" aria-label="Previous">&raquo;</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}
<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

templates/view.html
{% extends 'todo.html' %}
{% block title %}view{% endblock %}
{% block body %}
    <div class="border-0 border-dark text-break" style="width: 50%;margin: 3rem auto">
        <h3><span class="badge bg-success">Title</span></h3><br/>
        <p class="fs-2">{{ object.title }}</p><br/>
        <h3><span class="badge bg-success">Description</span></h3><br/>
        <p class="fs-3">{{ object.description }}</p><br/>
        <div class="d-md-flex justify-content-md-center">
            <a class="btn btn-lg btn-primary" href="{% url 'edit' object.pk %}">Edit</a>
        </div>

    </div>
{% endblock %}